version: 2

sources:
  - name: bigquery
    schema: raw_datasets
    tables:
     - name: devices_source
       columns:
        - name: id
          description: Unique identifier for the device.
          tests:
            - unique
            - not_null
     - name: stores_source
       columns:
        - name: id
          description: Unique identifier for the store.
          tests:
            - unique
            - not_null
     - name: transactions_source
       columns:
        - name: id
          description: Unique identifier for the transaction.
          tests:
            - unique
            - not_null

models:                   
      - name: transactions
        description: Staging table that stores all the transaction data
        columns:
          - name: transaction_id
            description: Unique identifier for the transaction.
            tests:
              - unique
              - not_null
          - name: store_id
            tests:
              - not_null
          - name: device_id 
            description: Unique identifier for the device.
            tests:
              - not_null
          - name: product_sku
            description: Unique identifier for the product unit
            tests:
              - not_null
          - name: type
            description: Type of device provided to stores. Value is between 1-5
            tests:
              - not_null
              - accepted_values:
                  values: [1, 2, 3, 4, 5]
                  quote: false             